name: CD

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test

      - name: Sign
        id: sign_jws
        uses: or13/jose-actions@v0.0.5
        with:
          resource: "jws"
          action: "sign"
          
          header: '{"kid":"did:web:or13.github.io:signor#0","alg":"ES256"}'
          payload: ${{ github.sha }}
          jwk: ${{ secets.DID_WEB_PRIVATE_KEY_JWK }}

      - run: |
          SIGNATURE=`echo "${{ steps.sign_jws.outputs.jws }}"`
          UPDATED=`jq ".signor.jose.signature=\"$SIGNATURE\"" package.json`
          echo "$UPDATED" > package.json

      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          
      - uses: stefanzweifel/git-auto-commit-action@v4

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}